cxx_binary(
  name = 'Demo',
  header_namespace = 'Demo',
  headers = subdir_glob([
    ('include', '**/*.hpp'),
  ]),
  srcs = glob([
    'src/**/*.cpp',
  ]),
  deps = [
    '//lib/TestLib:TestLib',
  ],
)